"""Helpers for the frozen final-analysis manifest."""

from __future__ import annotations

import hashlib
import copy
from pathlib import Path
from typing import Any

import yaml


def default_manifest_path(project_root: str | Path = ".") -> Path:
    return Path(project_root) / "experiments" / "final_manifest.yaml"


def load_final_manifest(path: str | Path | None = None) -> dict[str, Any] | None:
    manifest_path = Path(path) if path is not None else default_manifest_path()
    if not manifest_path.exists():
        return None
    with open(manifest_path) as f:
        return yaml.safe_load(f)


def normalise_config_path(path: str | Path) -> str:
    return str(Path(path).as_posix()).lstrip("./")


def _manifest_hash_config(config: dict[str, Any]) -> dict[str, Any]:
    """
    Return the config surface frozen by the final manifest.

    Final seed sweeps intentionally vary `training.seed`, while sensitivity runs
    may vary `inference.mode`. Those fields are checked explicitly as runtime
    metadata, so they are removed from the structural config fingerprint.
    Epoch count and scenario count stay in the hash because smoke overrides must
    never pass as final results.
    """
    cfg = copy.deepcopy(config)
    training = cfg.get("training")
    if isinstance(training, dict):
        training.pop("seed", None)
    inference = cfg.get("inference")
    if isinstance(inference, dict):
        inference.pop("mode", None)
    return cfg


def config_hash(config: dict[str, Any], *, manifest_fingerprint: bool = False) -> str:
    cfg = _manifest_hash_config(config) if manifest_fingerprint else config
    text = yaml.safe_dump(cfg, sort_keys=True)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]


def manifest_config_hash(config: dict[str, Any]) -> str:
    return config_hash(config, manifest_fingerprint=True)


def expected_config_hashes(manifest: dict[str, Any]) -> dict[str, str]:
    return {
        normalise_config_path(path): str(hash_value)
        for path, hash_value in manifest.get("deep_learning_config_hashes", {}).items()
    }


def _runtime_expectations(manifest: dict[str, Any]) -> dict[str, Any]:
    runtime = manifest.get("runtime_expectations", {})
    if "deep_learning" in runtime:
        return runtime.get("deep_learning", {})
    return runtime


def attach_manifest_metadata(
    metrics: dict[str, Any],
    *,
    config_path: str | Path | None,
    config: dict[str, Any],
    run_name: str,
    benchmark_name: str | None = None,
    manifest_path: str | Path | None = None,
) -> dict[str, Any]:
    """
    Add manifest version/config hash to metrics generated by final runs.

    The comparison layer requires this metadata so stale files with final-looking
    names are not silently included after the manifest is frozen.
    """
    manifest = load_final_manifest(manifest_path)
    if manifest is None:
        return metrics

    deep_configs = {
        normalise_config_path(p)
        for p in manifest.get("deep_learning_configs", [])
    }
    benchmark_runs = set(manifest.get("benchmark_run_names", []))
    cfg_norm = normalise_config_path(config_path) if config_path is not None else None

    is_final_deep = benchmark_name is None and cfg_norm in deep_configs
    is_final_benchmark = benchmark_name in benchmark_runs if benchmark_name is not None else False
    if not (is_final_deep or is_final_benchmark):
        return metrics

    metrics["final_manifest_version"] = manifest["version"]
    metrics["final_manifest_run_name"] = run_name
    if benchmark_name is not None:
        metrics["final_manifest_benchmark_name"] = benchmark_name
    if cfg_norm is not None:
        metrics["final_manifest_config"] = cfg_norm
        metrics["final_manifest_config_hash"] = manifest_config_hash(config)
        metrics["final_manifest_actual_config_hash"] = config_hash(config)
    if is_final_deep:
        training = config.get("training", {})
        inference = config.get("inference", {})
        metrics["final_manifest_seed"] = training.get("seed")
        metrics["final_manifest_epochs"] = training.get("epochs")
        metrics["final_manifest_inference_mode"] = inference.get("mode", "sample")
        metrics["final_manifest_n_scenarios"] = inference.get("n_scenarios")
    return metrics


def result_matches_manifest(
    stem: str,
    metrics: dict[str, Any],
    manifest: dict[str, Any],
    *,
    include_expected: bool = False,
    include_unseeded: bool = True,
) -> tuple[bool, str]:
    """
    Validate one metrics JSON against the frozen final-analysis manifest.

    Returns `(True, "ok")` when the file is admissible for thesis tables.
    Otherwise returns `(False, reason)` so callers can log why a file was skipped.
    """
    allowed = allowed_final_run_names(
        manifest,
        include_expected=include_expected,
        include_unseeded=include_unseeded,
    )
    if stem not in allowed:
        return False, "run stem is not listed in final manifest"

    version = manifest.get("version")
    if metrics.get("final_manifest_version") != version:
        return False, f"final_manifest_version is not {version}"

    run_name = metrics.get("final_manifest_run_name")
    if run_name is not None and run_name != stem:
        return False, f"final_manifest_run_name={run_name!r} does not match file stem"

    benchmark_runs = set(manifest.get("benchmark_run_names", []))
    if stem in benchmark_runs:
        if metrics.get("final_manifest_benchmark_name") != stem:
            return False, "benchmark result lacks matching final_manifest_benchmark_name"
        cfg_norm = metrics.get("final_manifest_config")
        hashes = expected_config_hashes(manifest)
        if cfg_norm in hashes and metrics.get("final_manifest_config_hash") != hashes[cfg_norm]:
            return False, "benchmark config hash does not match frozen manifest"
        return True, "ok"

    cfg_norm = normalise_config_path(metrics.get("final_manifest_config", ""))
    hashes = expected_config_hashes(manifest)
    if not cfg_norm or cfg_norm not in hashes:
        return False, "metrics JSON does not name a frozen final config"
    if metrics.get("final_manifest_config_hash") != hashes[cfg_norm]:
        return False, "config hash does not match frozen manifest"

    seeds = set(manifest.get("methodology", {}).get("seeds", []))
    if metrics.get("final_manifest_seed") not in seeds:
        return False, "seed is not in frozen seed sweep"

    runtime = _runtime_expectations(manifest)
    expected_mode = runtime.get(
        "inference_mode",
        manifest.get("methodology", {}).get("inference_primary", "sample"),
    )
    if metrics.get("final_manifest_inference_mode") != expected_mode:
        return False, "inference mode does not match frozen manifest"

    expected_epochs = runtime.get("epochs")
    if expected_epochs is not None and metrics.get("final_manifest_epochs") != expected_epochs:
        return False, "epoch count does not match frozen manifest"

    expected_scenarios = runtime.get("n_scenarios")
    if expected_scenarios is not None and metrics.get("final_manifest_n_scenarios") != expected_scenarios:
        return False, "scenario count does not match frozen manifest"

    return True, "ok"


def allowed_final_run_names(
    manifest: dict[str, Any],
    *,
    include_expected: bool = False,
    include_unseeded: bool = True,
) -> set[str]:
    """Return run stems allowed by the final manifest."""
    allowed = set(manifest.get("benchmark_run_names", []))
    seeds = manifest.get("methodology", {}).get("seeds", [])

    for cfg_path in manifest.get("deep_learning_configs", []):
        try:
            with open(cfg_path) as f:
                cfg = yaml.safe_load(f)
            run_name = cfg["output"]["run_name"]
        except Exception:
            continue
        if include_unseeded:
            allowed.add(run_name)
        for seed in seeds:
            allowed.add(f"{run_name}_seed{seed}_sample")
            if include_expected:
                allowed.add(f"{run_name}_seed{seed}_expected")
    return allowed
