#!/usr/bin/env python3
"""
Generate the tuned-run configs from HPO winner YAMLs.

Part of the tuned-performance workflow (kaggle_tuned_runner.ipynb). Takes the
four grid-HPO winner configs written by tune.py --out-config and stamps their
hyperparameters onto fresh copies of the frozen configs_final counterparts:

  * lstm_joint_dunnhumby_tuned          <- winner of lstm_joint_dunnhumby_final HPO
  * transformer_joint_dunnhumby_tuned   <- winner of transformer_joint_dunnhumby_final HPO
  * extension3_{lstm,transformer}_{none,static,dynamic,full}_dunnhumby_tuned
        <- winner of the corresponding extension3_*_full_dunnhumby_final HPO,
           transferred to ALL FOUR covariate variants so the ablation compares
           covariate sets under identical hyperparameters.

Only two things may differ from the configs_final counterpart:
  1. the HP_KEYS the grid search is allowed to touch (lr, hidden_size/dropout
     for LSTM; d_model/n_heads for the Transformer), and
  2. the epoch budget (--max_epochs; the fixed 150-epoch runs on Dunnhumby all
     terminated at the cap with early stopping never firing, so the tuned
     configuration lifts the cap and lets patience-20 early stopping decide).

Everything else (protocol, splits, scalers, loss, finetune, inference) is
asserted byte-identical to the frozen base config, so fixed-vs-tuned deltas
isolate the tuning effect.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Dotted keys the grid search may set (superset across samplers; keys absent
# from a winner are simply not transferred).
HP_KEYS = [
    ("training", "lr"),
    ("training", "weight_decay"),
    ("training", "max_grad_norm"),
    ("model", "hidden_size"),
    ("model", "dropout"),
    ("model", "d_model"),
    ("model", "n_heads"),
    ("model", "d_ff"),
    ("model", "n_layers"),
]

EXT3_VARIANTS = ("none", "static", "dynamic", "full")
ARCHITECTURES = ("lstm", "transformer")


def _flatten(node, prefix=""):
    """Flatten a nested dict into {dotted_key: value} for diffing."""
    out = {}
    if isinstance(node, dict):
        for k, v in node.items():
            out.update(_flatten(v, f"{prefix}{k}."))
    else:
        out[prefix[:-1]] = node
    return out


def _extract_hps(winner: dict) -> dict:
    """Pull the tunable hyperparameter values out of a winner config."""
    hps = {}
    for section, key in HP_KEYS:
        if key in winner.get(section, {}):
            hps[f"{section}.{key}"] = winner[section][key]
    return hps


def _build_tuned(base: dict, hps: dict, run_name: str, max_epochs: int) -> dict:
    tuned = yaml.safe_load(yaml.safe_dump(base))  # deep copy via round-trip
    for dotted, value in hps.items():
        section, key = dotted.split(".")
        tuned.setdefault(section, {})[key] = value
    tuned["training"]["epochs"] = max_epochs
    tuned["training"]["max_epochs"] = max_epochs
    tuned["output"]["run_name"] = run_name
    return tuned


def _assert_parity(base: dict, tuned: dict, config_name: str, max_epochs: int) -> list[str]:
    """Assert tuned differs from base ONLY in HP keys, epoch budget, run_name.

    Returns the human-readable list of changed keys for the summary print.
    """
    allowed = {f"{s}.{k}" for s, k in HP_KEYS} | {
        "training.epochs",
        "training.max_epochs",
        "output.run_name",
    }
    flat_base, flat_tuned = _flatten(base), _flatten(tuned)
    if set(flat_base) != set(flat_tuned):
        extra = set(flat_tuned) ^ set(flat_base)
        raise AssertionError(f"{config_name}: key set drift vs base config: {sorted(extra)}")
    changed = sorted(k for k in flat_base if flat_base[k] != flat_tuned[k])
    illegal = [k for k in changed if k not in allowed]
    if illegal:
        raise AssertionError(
            f"{config_name}: non-hyperparameter keys changed vs configs_final: {illegal}"
        )
    if flat_tuned["training.max_epochs"] != max_epochs:
        raise AssertionError(f"{config_name}: max_epochs not applied")
    return [f"{k}: {flat_base[k]!r} -> {flat_tuned[k]!r}" for k in changed]


def _write(tuned: dict, out_dir: Path, name: str, base_path: Path, winner_path: Path):
    out_path = out_dir / f"{name}.yaml"
    header = (
        f"# Auto-generated by scripts/make_tuned_configs.py\n"
        f"# Base (frozen fixed-HP config): {base_path}\n"
        f"# Hyperparameters from HPO winner: {winner_path}\n"
        f"# Tuned-performance analysis config — NOT part of the frozen thesis\n"
        f"# evidence set (experiments/final_manifest.yaml).\n"
    )
    out_path.write_text(header + yaml.safe_dump(tuned, sort_keys=False, default_flow_style=False))
    return out_path


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--winner_main_lstm", required=True,
                   help="Winner YAML of the lstm_joint_dunnhumby_final HPO study.")
    p.add_argument("--winner_main_transformer", required=True,
                   help="Winner YAML of the transformer_joint_dunnhumby_final HPO study.")
    p.add_argument("--winner_ext3_lstm", required=True,
                   help="Winner YAML of the extension3_lstm_full_dunnhumby_final HPO study.")
    p.add_argument("--winner_ext3_transformer", required=True,
                   help="Winner YAML of the extension3_transformer_full_dunnhumby_final HPO study.")
    p.add_argument("--configs_final_dir", default=str(PROJECT_ROOT / "experiments/configs_final"))
    p.add_argument("--out_dir", default=str(PROJECT_ROOT / "experiments/configs_tuned"))
    p.add_argument("--max_epochs", type=int, default=250,
                   help="Epoch cap for tuned finals (fixed runs hit the 150 cap; "
                        "early stopping patience 20 decides the actual length).")
    args = p.parse_args()

    final_dir = Path(args.configs_final_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    jobs = []  # (tuned_name, base_path, winner_path)
    winners = {
        "lstm": Path(args.winner_main_lstm),
        "transformer": Path(args.winner_main_transformer),
    }
    for arch in ARCHITECTURES:
        jobs.append((
            f"{arch}_joint_dunnhumby_tuned",
            final_dir / f"{arch}_joint_dunnhumby_final.yaml",
            winners[arch],
        ))
    ext3_winners = {
        "lstm": Path(args.winner_ext3_lstm),
        "transformer": Path(args.winner_ext3_transformer),
    }
    for arch in ARCHITECTURES:
        for variant in EXT3_VARIANTS:
            jobs.append((
                f"extension3_{arch}_{variant}_dunnhumby_tuned",
                final_dir / f"extension3_{arch}_{variant}_dunnhumby_final.yaml",
                ext3_winners[arch],
            ))

    written = []
    for name, base_path, winner_path in jobs:
        if not base_path.exists():
            raise FileNotFoundError(f"Base config missing: {base_path}")
        if not winner_path.exists():
            raise FileNotFoundError(f"Winner config missing: {winner_path}")
        base = yaml.safe_load(base_path.read_text())
        winner = yaml.safe_load(winner_path.read_text())
        hps = _extract_hps(winner)
        tuned = _build_tuned(base, hps, name, args.max_epochs)
        changes = _assert_parity(base, tuned, name, args.max_epochs)
        out_path = _write(tuned, out_dir, name, base_path, winner_path)
        written.append(out_path)
        print(f"[make_tuned_configs] {name}")
        for line in changes:
            print(f"    {line}")

    if len(written) != 10:
        raise AssertionError(f"Expected 10 tuned configs, wrote {len(written)}")
    print(f"\n[make_tuned_configs] Wrote {len(written)} configs to {out_dir}")


if __name__ == "__main__":
    main()
